---
config_dir: "{{ ansible_facts['user_dir'] }}/.config"
dotfiles_dir: "{{ ansible_facts['user_dir'] }}/.dotfiles"

dotfiles_repo: "https://github.com/shricodev/dotfiles.git"

ansible_user: "shricodev"

go:
  packages:
    - package: github.com/air-verse/air@latest
      cmd: air

    - package: github.com/melkeydev/go-blueprint@latest
      cmd: go-blueprint

    - package: github.com/pressly/goose/v3/cmd/goose@latest
      cmd: goose

    - package: github.com/rakyll/hey@latest
      cmd: hey

    - package: github.com/joshmedeski/sesh@latest
      cmd: sesh

    - package: github.com/spf13/cobra-cli@latest
      cmd: cobra-cli
