---
- name: Create the '$HOME/.config/redshift' directory if not exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/redshift"
    mode: "0755"
    state: directory

- name: Create symlink of files to '$HOME/.config/redshift' directory
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_facts['user_dir'] }}/.config/redshift"
    state: link
    force: true
