add_newline = false
format = """
$username\
$directory\
$git_branch\
$git_state\
$python\
$cmd_duration\
$character"""

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"

[directory]
read_only = " ğŸ”’"

[git_branch]
symbol = "ï˜ "
disabled = false

# This makes the terminal quite slow sometimes in certain folders. So disabling it for now.
# [git_status]
# disabled = false
# diverged = "ó°¦»"

[cmd_duration]
# Only show the time duration when above 5 minutes
min_time = 200_000
format = 'took [$duration](bold yellow) '

[git_state]
disabled = false

[python]
format = "[($virtualenv )](bold yellow)"
