---
common_packages:
  - git
  - jq
  - nodejs
  - xsel
  - fzf
  - curl
  - unzip
  - neovim
  - python3
  - python3-pip
  - fish
  - htop
  - zoxide
  - fuse-sshfs
  - asciinema
  - trash-cli
  - aria2
  - ncdu
