---
- name: Enable terra COPR repository for ghostty
  become: true
  community.general.copr:
    name: pgdev/ghostty
    state: enabled

- name: Install ghostty
  become: true
  ansible.builtin.dnf:
    name: ghostty
    state: present

- name: Create the '$HOME/.config/ghostty' directory if not exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/ghostty"
    mode: "0755"
    state: directory

- name: Create symlink of files to '$HOME/.config/ghostty' directory
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_facts['user_dir'] }}/.config/ghostty"
    state: link
    force: true
