format = """
$username\
$directory\
$git_branch\
$git_status\
$package\
$python\
$java\
$rust\
$golang\
$docker_context\
$nodejs\
$cmd_duration\
$line_break\
$character"""

[git_status]
disabled = false

[username]
format = '[$user]($style) in '

[java]
style = "bold yellow"

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[cmd_duration]
format = 'took [$duration]($style) '
style = "bold yellow"

[directory]
style = "bold blue"
read_only = " "
read_only_style = "yellow"
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = "⬢ "

[rust]
symbol = " "
