format = """
$username\
$directory\
$git_branch\
$git_status\
$package\
$python\
$java\
$rust\
$golang\
$docker_context\
$nodejs\
$cmd_duration\
$line_break\
$character"""

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
staged = '[++\($count\)](green)'
deleted = 'ğŸ—‘ï¸'

[username]
format = '[$user]($style) in '

[java]
style = "bold yellow"

[character]
success_symbol = "[â¯](bold purple)"
error_symbol = "[â¯](red)"
vicmd_symbol = "[â®](green)"

[cmd_duration]
format = 'took [$duration]($style) '
style = "bold yellow"

[directory]
style = "bold blue"
read_only = " ï ½"
read_only_style = "yellow"
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = "ï˜ "

[nodejs]
symbol = "â¬¢ "

[rust]
symbol = "î¨ "
