---
- name: Enable terra COPR repository for ghostty
  become: true
  community.general.copr:
    name: scottames/ghostty
    state: enabled

- name: Install ghostty
  become: true
  ansible.builtin.dnf:
    name: ghostty
    state: present
