---
- name: Create the '$HOME/.config/bat' directory if not exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/bat"
    mode: "0755"
    state: directory

- name: Create symlink of files to '$HOME/.config/bat' directory
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_facts['user_dir'] }}/.config/bat"
    state: link
    force: true
